### ISSUE TITLE
NLB Support (AWS Launched TLS Termination for NLB)

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/kube-ingress-aws-controller#236] opened 2019-01-24 19:40 UTC
AWS Network Load Balancer (NLB) now supports TLS termination, so we might want to get rid of ALB: https://aws.amazon.com/blogs/aws/new-tls-termination-for-network-load-balancers/

**Comment by Passpes** [comment] 2019-02-19 17:22
is this feature added already?

**Comment by mikkeloscar** [comment] 2019-02-19 17:31
No, not yet!

**Comment by so0k** [comment] 2019-02-25 04:49
We've been using NLB with TLS termination for our clusters (managed by Terraform for now). Interesting to note no SNI support, so will need to provision an NLB for each cert that matches the ingress host requests.

**Comment by joberdick** [comment] 2019-03-15 00:21
@so0k This seems impractical without SNI support. You can only have a few NLBs in an account. Bummer. I was interested in this.

**Comment by so0k** [comment] 2019-03-15 00:24
We switched back to Cert Manager and TLS termination at our ingress proxy due to some WSS issues. It’s been crazy, but we see the light at the end of the tunnel

**Comment by szuecs** [comment] 2019-03-16 19:23
@so0k did you used kube-ingress-aws-controller + skipper to do websockets (WSS?)?
If so we introduced a bug in skipper with a loadbalancer refactoring that was fixed in https://github.com/zalando/skipper/releases/tag/v0.10.186.

**Comment by andreasph** [comment] 2019-10-20 22:55
@joberdick since a little more than a month NLB has SNI support (https://aws.amazon.com/about-aws/whats-new/2019/09/elastic-load-balancing-network-load-balancers-now-supports-multiple-tls-certificates-using-server-name-indication/)

I'm currently using kube-ingress-aws-controller + ingress-nginx (no skipper) and I have a problem with http2 requests forwarded to the targets by the ALB as http1.1: this prevents us to use it for grpc services

**Comment by szuecs** [comment] 2019-10-21 12:55
@andreasph just to make sure the basics are met: Do you have a https target group (`ALB -> nginx`)?

**Comment by andreasph** [comment] 2019-10-21 13:03
@szuecs the whole setup is working fine with http ingress. gprc is supported as well by nginx ingress, the problem is that the external HTTP2 grpc request is then forwarded by the ALB to the target group as HTTP/1.1

it is somehow similar to this problem: https://github.com/kubernetes/ingress-nginx/issues/2963#issuecomment-415141659

does skipper support grpc ingress?
I preferred to use nginx ingress rather than skipper for broader support and easier troubleshooting

**Comment by andreasph** [comment] 2019-10-21 13:07
@szuecs unless you where suggesting to have an https listener as target on nginx side: that I don't have and I don't want to have. I'd need to provision certs on the nginx ingress side and lose the whole benefit of having tls termination at ALB level

**Comment by szuecs** [comment] 2019-10-21 13:29
@andreasph H2 often only works for https. H2 over plain TCP is called H2C, so maybe AWS ALB does not support it, or you GRPC backend server handler does not support it.

Does Nginx support H2C?
Skipper does not, but I want to build it in the future.

**Comment by andreasph** [comment] 2019-10-21 15:29
@szuecs trying to test H2 instead of H2C but the problem is that as you suggested I'd need an https target group, while it was created as http (https://github.com/zalando-incubator/kube-ingress-aws-controller/tree/master/aws#L213)

I don't find how to override the target group protocol

**Comment by szuecs** [comment] 2019-10-21 15:35
@andreasph I guess we need to have a PR for enabling TLS on the TargetGroup. In a test cluster I would stop the kube-ingress-aws-controller and try to modify the ALB TG manually. Later you can delete the CF stack and let kube-ingress-aws-controller recreate the CF stack, otherwise you would likely have a broken CF stack

**Comment by andreasph** [comment] 2019-10-21 15:42
@szuecs unluckly there's no option to update the protocol of the target group once it's created
I will see if I have time to create a PR for it here

**Comment by andreasph** [comment] 2019-10-23 12:52
@szuecs I did some test with both HTTPS ALB->HTTPS NGINX INGRESS->GRPC and HTTPS ALB->HTTP NGINX INGRESS->GRPC and the results are the same
inspecting the grpc service with reflections works, calling grpc methods not

I still have to test HTTPS ALB->HTTPS NGINX INGRESS->GRPCS

**Comment by szuecs** [comment] 2019-10-31 11:28
NLB is now supported https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/242

**Closed by szuecs** 2019-10-31 11:28 UTC
Labels: enhancement
