### ISSUE TITLE
ALB Target group created without any EC2 targets

### ISSUE THREAD

**Issue by sdevang** [zalando-incubator/kube-ingress-aws-controller#121] opened 2018-02-06 17:49 UTC
Hi,

I have deployed ingress controller and it can discover the SG, EC2 Instances and Auto Scaling Group and it creates the ALB when there is a new ingress... however the ALB created by Ingress does not have any EC2 instances registered as targets.

Any idea ?

Regards,
Dev

**Comment by mikkeloscar** [comment] 2018-02-06 18:46
What version of the controller are you running?

Can you post the logs from it?

**Comment by szuecs** [comment] 2018-02-06 19:46
@sdevang please check if the controller has the rights to attach/detach ec2 instances to the elastic loadbalancer target group. https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/deploy/requirements.md shows the list of access rights that it needs.

**Comment by sdevang** [comment] 2018-02-07 09:54
@mikkeloscar : here comes the logs.

2018/02/06 16:12:09 starting /bin/kube-ingress-aws-controller
2018/02/06 16:12:11 controller manifest:
2018/02/06 16:12:11 	kubernetes API server:
2018/02/06 16:12:11 	Cluster ID: xxxxxxx
2018/02/06 16:12:11 	vpc id: vpc-xxxxxxx
2018/02/06 16:12:11 	instance id: i-xxxxxxxxxxxx
2018/02/06 16:12:11 	security group id: sg-xxxxxxx
2018/02/06 16:12:11 	internal subnet ids: [subnet-xxxxxx subnet-xxxxxxx subnet-xxxxxxx]
2018/02/06 16:12:11 	public subnet ids: [subnet-xxxxxx subnet-xxxxxxx subnet-xxxxxxx]
2018/02/06 16:12:11 	EC2 filters: tag:kubernetes.io/cluster/xxxxxx=owned tag-key=k8s.io/role/node

2018/02/07 09:52:15 updated ingress default/my-nginx with DNS name "xxxxxx-lb-1hrxddetdnqk4-xxxxxxx.eu-west-1.elb.amazonaws.com"
2018/02/07 09:52:15 Start polling sleep 30s
2018/02/07 09:52:45 Found 1 ingresses
2018/02/07 09:52:45 Found 1 stacks
2018/02/07 09:52:45 Found 1 auto scaling groups
2018/02/07 09:52:45 Found 0 single instances
2018/02/07 09:52:45 Found 5 EC2 instances
2018/02/07 09:52:45 Have 1 models
2018/02/07 09:52:45 updated ingress default/my-nginx with DNS name "xxxxxxx-lb-1hrxddetdnqk4-xxxxxxxx.eu-west-1.elb.amazonaws.com"
2018/02/07 09:52:45 Start polling sleep 30s
2018/02/07 09:53:15 Found 1 ingresses
2018/02/07 09:53:16 Found 1 stacks
2018/02/07 09:53:16 Found 1 auto scaling groups
2018/02/07 09:53:16 Found 0 single instances
2018/02/07 09:53:16 Found 5 EC2 instances
2018/02/07 09:53:16 Have 1 models
2018/02/07 09:53:16 updated ingress default/my-nginx with DNS name "xxxxxxxx-lb-1hrxddetdnqk4-xxxxxxxxxx.eu-west-1.elb.amazonaws.com"
2018/02/07 09:53:16 Start polling sleep 30s

**Comment by sdevang** [comment] 2018-02-07 09:56
@szuecs : I followed the requirements as mentioned in the requirements.md file and all the worker node have IAM Role which has an IAM policy which allows them to detach and attach instances.

**Comment by sdevang** [comment] 2018-02-07 09:58
<img width="1207" alt="screen shot 2018-02-07 at 09 57 43" src="https://user-images.githubusercontent.com/11915431/35910081-692435fa-0bed-11e8-99fc-918370a6e591.png">

**Comment by szuecs** [comment] 2018-02-07 10:18
@sdevang can you show us the CF stack events, please?
I think there we should be able to spot the problem.

**Comment by sdevang** [comment] 2018-02-07 10:46
@szuecs : Here you go.

```
	08:50:05 UTC+0000	UPDATE_COMPLETE	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
08:50:04 UTC+0000	UPDATE_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
08:49:55 UTC+0000	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	User Initiated
04:50:06 UTC+0000	UPDATE_COMPLETE	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
04:50:05 UTC+0000	UPDATE_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
04:49:56 UTC+0000	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	User Initiated
03:50:07 UTC+0000	UPDATE_COMPLETE	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
03:50:06 UTC+0000	UPDATE_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
03:49:55 UTC+0000	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	User Initiated
00:50:06 UTC+0000	UPDATE_COMPLETE	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
00:50:05 UTC+0000	UPDATE_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
00:49:56 UTC+0000	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	User Initiated
2018-02-06	Status	Type	Logical ID	Status Reason
23:50:06 UTC+0000	UPDATE_COMPLETE	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
23:50:05 UTC+0000	UPDATE_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
23:49:56 UTC+0000	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	User Initiated
22:50:06 UTC+0000	UPDATE_COMPLETE	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
22:50:05 UTC+0000	UPDATE_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
22:49:56 UTC+0000	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	User Initiated
21:50:06 UTC+0000	UPDATE_COMPLETE	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
21:50:06 UTC+0000	UPDATE_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
21:49:56 UTC+0000	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	User Initiated
19:50:06 UTC+0000	UPDATE_COMPLETE	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
19:50:05 UTC+0000	UPDATE_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
19:49:56 UTC+0000	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	User Initiated
18:50:07 UTC+0000	UPDATE_COMPLETE	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
18:50:06 UTC+0000	UPDATE_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
18:49:55 UTC+0000	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	User Initiated
17:27:13 UTC+0000	CREATE_COMPLETE	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing	
17:27:12 UTC+0000	CREATE_COMPLETE	AWS::ElasticLoadBalancingV2::Listener	HTTPSListener	
17:27:11 UTC+0000	CREATE_COMPLETE	AWS::ElasticLoadBalancingV2::Listener	HTTPListener	
17:27:11 UTC+0000	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::Listener	HTTPSListener	Resource creation Initiated
17:27:11 UTC+0000	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::Listener	HTTPListener	Resource creation Initiated
17:27:10 UTC+0000	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::Listener	HTTPListener	
17:27:10 UTC+0000	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::Listener	HTTPSListener	
17:27:08 UTC+0000	CREATE_COMPLETE	AWS::ElasticLoadBalancingV2::LoadBalancer	LB	
17:25:29 UTC+0000	CREATE_COMPLETE	AWS::ElasticLoadBalancingV2::TargetGroup	TG	
17:25:28 UTC+0000	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::LoadBalancer	LB	Resource creation Initiated
17:25:28 UTC+0000	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::TargetGroup	TG	Resource creation Initiated
17:25:28 UTC+0000	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::TargetGroup	TG	
17:25:27 UTC+0000	CREATE_IN_PROGRESS	AWS::ElasticLoadBalancingV2::LoadBalancer	LB	
17:25:24 UTC+0000	CREATE_IN_PROGRESS	AWS::CloudFormation::Stack	xxxxxxxx-41bec06-internet-facing

```

**Comment by szuecs** [comment] 2018-02-07 11:27
@sdevang as you do not use the multiple ASG or EC2 node feature, can you use the latest version from 0.4.x, please?
0.5.x was not really tested yet from us.

**Comment by oliver-whiteman** [comment] 2018-03-13 11:59
Did you manage to make much headway with this?

I also have a target group that is created as empty and not certain why

**Comment by mikkeloscar** [comment] 2018-03-13 12:25
@oliver-whiteman Are you running the latest version of the controller? Can you post the logs?

**Comment by oliver-whiteman** [comment] 2018-03-13 12:56
I am running this: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:latest
so I think so

What logs are you after?

**Comment by mikkeloscar** [comment] 2018-03-13 13:04
@oliver-whiteman the logs of the kube-ingress-aws-controller. I assume the problem is related to the controller not finding any instances for the cluster, but the logs would help understand what is going on.

And you are using the latest version like that.

Thanks!

**Comment by oliver-whiteman** [comment] 2018-03-13 13:08
Yes I would say so:

2018/03/13 13:07:23 Found 2 ingresses
2018/03/13 13:07:23 Found 1 stacks
2018/03/13 13:07:23 Found 0 auto scaling groups
2018/03/13 13:07:23 Found 0 single instances
2018/03/13 13:07:23 Found 0 EC2 instances
2018/03/13 13:07:23 Have 1 models

**Comment by mikkeloscar** [comment] 2018-03-13 13:20
Then you probably have the wrong tags on your instances. The needed tags are described here: https://github.com/zalando-incubator/kube-ingress-aws-controller#how-it-works

**Comment by oliver-whiteman** [comment] 2018-03-13 13:36
Ah ok, I added this to the existing cluster but doesnt look like it did the update

Have added it in manually now and seems better. May try to recreate the cluster to see if it works that way without intervention

Thanks!

**Comment by szuecs** [comment] 2018-04-05 13:07
I close this issue, because for me it seems not to be the issue of this project.
Maybe better to have a separate documentation issue.

**Closed by szuecs** 2018-04-05 13:07 UTC
