### ISSUE TITLE
Allow specifying empty ingress class in ingress-class-filter parameter

### ISSUE THREAD

**Issue by dintel** [zalando-incubator/kube-ingress-aws-controller#291] opened 2019-11-12 09:38 UTC
When specifying list of ingress classes that controller should handle allow specifying empty name. Currently when specifying ingress-class-filter parameter controller will ignore ingress objects with empty or missing `kubernetes.io/ingress.class` annotation.

**Comment by jhohertz** [comment] 2019-11-12 14:41
Isn't this the intended behaviour? If you don't wish to filter ingress classes, do not specify an ingress-class-filter? Maybe I am missing something?

**Comment by dintel** [comment] 2019-11-12 16:58
In our setup I am trying to setup 2 ingress controllers such that one will handle specific ingress class X and another should handle Y and <empty> class (or class is not set at all).
First controller has `ingress-class-filter=X` and works correctly. Second controller has `ingress-class-filter=Y,` (note the comma in the end), but it only manages ingresses with class Y.
I tried running another controller without `ingress-class-filter` set, but then it interferes with all other controllers because it manages all ingress objects.

**Comment by jhohertz** [comment] 2019-11-12 18:39
I see what you mean now.

**Comment by szuecs** [comment] 2019-11-12 21:14
Please also add some docs for the pr, thanks

**Comment by dintel** [comment] 2019-11-17 11:21
@szuecs Added mention of the behavior in README file.

**Comment by szuecs** [comment] 2019-11-23 11:16
Merged the pr, release should follow automatically soon

**Closed by szuecs** 2019-11-23 11:16 UTC
