### ISSUE TITLE
doesn't clean up invalid target groups

### ISSUE THREAD

**Issue by universam1** [zalando-incubator/kube-ingress-aws-controller#475] opened 2022-02-08 14:23 UTC
Invalid, non-existent target groups registrations on autoscaling groups are not removed, causing errors such as that scaling is blocked.

Invalid registrations can appear when CFN replaces a target group which happens due to various reasons.

Looks like a [bug that the controller keeps non-existent target groups](https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/9f2db47914ab9aa425f7232e427a9f6f5aed7de6/aws/asg.go#L175-L214) registered because it cannot determine the ownership - given that the TG is gone and thus not enumerable.
Probably this logic can be simplified to remove any invalid registration, even when it lost track of.

@AlexanderYastrebov @szuecs

**Comment by szuecs** [comment] 2022-02-08 16:13
The problem could be if you mix manual and our CF stack related Load Balancers. If you would clean up the ones that are not having our Tag, then you clean up things you do not own.

**Comment by universam1** [comment] 2022-02-09 09:07
> The problem could be if you mix manual and our CF stack related Load Balancers. If you would clean up the ones that are not having our Tag, then you clean up things you do not own.

This issue is only about cleaning up **non-existent** thus invalid target groups. I cannot think of a reason why it should not remove such broken links in any case

**Comment by szuecs** [comment] 2022-02-09 09:22
@universam1 but you link to code path which tests for ownership. If you like to add some cleanup code here you would need to check the Tag anyways, because we should only care about our resources. Other controllers need to keep track on theirs and manual created ones need to be manually maintained or you have a custom control loop that cleans up "broken things".
I don't see that this controller cleans up resource created by others and I do not believe right now that Cloudformation will create such a state. So right now it would be a won't fix, IMO.

**Comment by mikkeloscar** [comment] 2022-02-09 09:40
@universam1 @szuecs We do try to cleanup non-existing target groups: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/9f2db47914ab9aa425f7232e427a9f6f5aed7de6/aws/asg.go#L176

If there are cases not handled by the current logic then it makes sense to handle that especially if it's is caused by the controller. We have a disconnect between target group creation/deletion (Cloudformation) and attaching to ASG which is done in the referenced controller code. As already stated checking for the ownership of target groups and checking for non-existing target groups is not the same.

**Comment by universam1** [comment] 2022-02-09 09:42
@szuecs Maybe I was too deep into the solution to explain verbose enough that this is a bug created by this controller.
I believe there are other cases such as #446 that will cause a replacement of the TG CFN resource, but at least this one here you can replay consistently:

1. change access from HostPort to AWSCNI
2. CFN creates an new TG
3. CFN deletes the TG linked to the ASG by this controller
3. The ASG is now in error state

Problem is that this reference in the ASG is invalid, and the **tags are gone** hence this controller will not clean up any more.
How to approach this bug is the question - where I believe it could be [simple](https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/475#issuecomment-1033522677)

**Comment by universam1** [comment] 2022-02-09 11:10
@szuecs @mikkeloscar I've ran some more debug sessions and found the actual bug that the cleanup would work as expected but it is simply not called. Thanks for the discussion.

Given that there is **only one TG and it is of type IP** created by the stack, we are not callling `updateTargetGroupsForAutoScalingGroup` ->  `detachTargetGroupsFromAutoScalingGroup`

https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/9f2db47914ab9aa425f7232e427a9f6f5aed7de6/aws/adapter.go#L597-L609

That means this [condition](https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/9f2db47914ab9aa425f7232e427a9f6f5aed7de6/aws/adapter.go#L598) is oversimplified

**Comment by universam1** [comment] 2022-02-09 13:38
From my tests removing this condition does solve the problem just fine!
https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/9f2db47914ab9aa425f7232e427a9f6f5aed7de6/aws/adapter.go#L598-L600

However, this practically reverts #144 and might open up #139 again - so wondering if we can cover #144 differently @mikkeloscar such as to filter calls where 'targetGroupARNs' is 'nil'?

**Comment by mikkeloscar** [comment] 2022-02-09 14:35
@universam1 We should just move the `if len(targetGroupARNs) == 0 {` logic inside `updateTargetGroupsForAutoScalingGroup` so it has the same effect as #141 but also can clean up non-existing target groups from the ASGs.

**Comment by universam1** [comment] 2022-02-09 14:46
Thanks - sounds great! 
Would you @mikkeloscar agree that this is already implemented in meantime via #436 ?

https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/9f2db47914ab9aa425f7232e427a9f6f5aed7de6/aws/asg.go#L216-L226

**Comment by szuecs** [comment] 2022-02-09 20:35
Yes I agree that this  is already implemented in meantime via https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/436

**Closed** 2022-02-10 09:55 UTC
